spring.datasource.url: jdbc:mysql://localhost:3306/MyProject?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: update

spring:
  liquibase:
    enabled: false
    change-log: classpath:database_changelog.xml
    url: jdbc:mysql://localhost:3306/myproject?serverTimezone=UTC
    user: root
    password: testtest