spring.datasource.url: jdbc:mysql://localhost:3306/MyProject?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

spring:
  liquibase:
    enabled: false
    change-log: classpath:database_changelog.xml
    url: jdbc:mysql://localhost:3306/myproject?serverTimezone=UTC
    user: root
    password: testtest

spring.mail.host: smtp.yandex.ru
spring.mail.username: ivanivanov1977.ivashka@yandex.ru
spring.mail.password: '03081977'
spring.mail.port: 465
spring.mail.protocol: smtps
mail.debug: true